### ISSUE TITLE
repository does not exist anymore

### ISSUE THREAD

**Issue by bert2002** [opauth/google#10]
Looks like the README is not up to date :) 

$ git clone git://github.com/uzyn/opauth-google.git Google
Cloning into 'Google'...
fatal: remote error: 
  Repository not found.
$

**Comment by x29a** [comment]
The readme needs updating as done in [this PR](https://github.com/opauth/google/pull/9/files)

**Comment by uzyn** [comment]
#9 merged. Closing this.
Thanks.
